optimize:
  redstone-limit: 15 
  tick-rate: 20    
  chunk-loading: true
  # Límites de entidades por chunk:
  entity-limits:
    mobs: 100       
    animals: 50       
    items: 200         
  entity-unload-time: 600  # Tiempo en segundos después del cual las entidades inactivas se descargan

# Configuración de eventos
events:
  player_join:
    message: "¡Bienvenido al servidor, %player%!"
    log: true  

  player_quit:
    message: "¡Adiós, %player%! Hasta la próxima."
    log: true  

  # Prohibir ítems específicos
  prohibited_items:
    message: "¡Este artículo está prohibido!"
    items:
      - "DIAMOND_SWORD"
      - "NETHERITE_SWORD"
      - "TNT"


  # Filtro de chat
  chat:
    enable_filter: true  # Habilitar un filtro de chat para evitar palabras ofensivas
    allowed_words: 
      - "minecraft"
      - "server"
    blocked_words: 
      - "swearword1"
      - "swearword2"

# Configuración del comando RTP (teletransportación aleatoria)
rtp:
  world: world  
  radius: 1000
  message: "§a¡Has sido teletransportado aleatoriamente!" 
  blacklist:
    worlds:
      - "world_nether"
      - "world_the_end" 
    biomes:
      - "DESERT"
      - "OCEAN"
  cooldown: 30  # Cooldown en segundos
  messages:
    no_permission: "§cNo tienes permiso para usar este comando."
    wait_time: "§cDebes esperar %time% segundos antes de usar el comando nuevamente."
    blacklisted_world: "§cNo puedes teletransportarte a este mundo."
    no_valid_location: "§cNo se pudo encontrar un lugar válido para teletransportarse."
    console_command: "Este comando solo puede ser ejecutado por jugadores."

# Configuración del spawn
spawn:
  world: world 
  x: 0
  y: 100 
  z: 0
  message_on_spawn: "¡Bienvenido al servidor técnico, %player%!"
