name: SimplePlugin
version: 1.0
main: com.simpleplugin.Main
api-version: 1.13
commands:
  tpa:
    description: Solicita teletransportarse a otro jugador.
    usage: /<command> <jugador>
  tpaccept:
    description: Acepta una solicitud de teletransportación.
    usage: /<command>
  tpdeny:
    description: Niega una solicitud de teletransportación.
    usage: /<command>
  analyze:
    description: Analiza las estadísticas del servidor.
    usage: /<command>
  reloadconfig:
    description: Recarga la configuración del plugin.
    usage: /<command>
  rtp:
    description: Teletransporta al jugador a una ubicación aleatoria.
    usage: /<command>
  setspawn:
    description: Establece el punto de spawn del servidor.
    usage: /<command>
permissions:
  simpleplugin.rtp:
    description: Permite usar el comando RTP.
    default: true
